apiVersion: apps.openliberty.io/v1
kind: OpenLibertyApplication
metadata:
  name: getting-started
  labels:
    name: system
spec:
  applicationImage: icr.io/appcafe/open-liberty
  expose: true
  service:
    type: ClusterIP
  env:
    - name: WLP_LOGGING_MESSAGE_FORMAT
      value: "json"
    - name: WLP_LOGGING_MESSAGE_SOURCE
      value: "message,trace,accessLog,ffdc,audit"
